spring.application.name=banking-transaction
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_transaction
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.user.username=anant
spring.security.user.password=anant123